version: '3.7'

services:
  nginx:
    image: nginx:1.13.8
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx

  backend:
    image: backend
    build: backend
    env_file: .env
    volumes:
      - ./backend/code:/code

  frontend:
    build:
      context: frontend
      target: builder
    env_file: .env
    volumes:
      - ./frontend/code:/code
      - /code/node_modules

  postgres:
    image: postgres:10.1
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2.11

volumes:
  postgres-data:
