"""add group to all bill items

Revision ID: 0f67b8babc36
Revises: d9a7e1931269
Create Date: 2018-11-13 20:25:10.075169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f67b8babc36'
down_revision = 'd9a7e1931269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_items', sa.Column('group_uid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(op.f('fk_bill_items_group_uid_groups'), 'bill_items', 'groups', ['group_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_bill_items_group_uid_groups'), 'bill_items', type_='foreignkey')
    op.drop_column('bill_items', 'group_uid')
    # ### end Alembic commands ###
