"""create bill item

Revision ID: 12105e0d312b
Revises: 2bacd3a79b4b
Create Date: 2018-10-18 13:05:15.661687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "12105e0d312b"
down_revision = "2bacd3a79b4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_items",
        sa.Column("uid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("bill_uid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_uid"], ["bills.uid"], name=op.f("fk_bill_items_bill_uid_bills")
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_bill_items")),
    )
    op.alter_column("bills", "billed_at", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bills", "billed_at", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("bill_items")
    # ### end Alembic commands ###
