"""add group

Revision ID: d9a7e1931269
Revises: 12105e0d312b
Create Date: 2018-11-06 14:58:19.041015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9a7e1931269'
down_revision = '12105e0d312b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('wallet_uid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_uid'], ['wallets.uid'], name=op.f('fk_groups_wallet_uid_wallets')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_groups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
