"""add computing of bill items

Revision ID: ec0e810d79ca
Revises: 0f67b8babc36
Create Date: 2018-11-15 09:48:26.806747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec0e810d79ca"
down_revision = "0f67b8babc36"
branch_labels = None
depends_on = None


def compute(context):
    parameters = context.get_current_parameters()
    value = parameters.get("value")
    quantity = parameters.get("quantity")
    return value * quantity if value and quantity else 0


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_items",
        sa.Column(
            "total", sa.Float(), nullable=False, default=compute, onupdate=compute
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_items", "total")
    # ### end Alembic commands ###
